# Generated by Django 5.1.4 on 2024-12-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
