# Generated by Django 5.1.4 on 2025-01-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_on']},
        ),
    ]
